nelmio_cors:
    defaults:
        allow_credentials: true

        allow_origin: ['*']
        allow_headers: ['X-Custom-Auth', 'Content-Type']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        max_age: 3600

    # For pre-flight requests (OPTIONS) for CORS
    paths:
        '^/': ~
